CREATE TABLE TBESTADO (
	IDESTADO BIGINT NOT NULL AUTO_INCREMENT,
	TXNOME VARCHAR(80) NOT NULL,
	TXSIGLA VARCHAR(3) NOT NULL,
	CONSTRAINT PK_ESD PRIMARY KEY (IDESTADO)
) ENGINE=INNODB DEFAULT CHARSET=UTF8;