CREATE TABLE TBCIDADE (
	IDCIDADE BIGINT NOT NULL AUTO_INCREMENT,
	IDESTADO BIGINT NOT NULL,
	TXNOME VARCHAR(80) NOT NULL,
	CONSTRAINT PK_CDD PRIMARY KEY (IDCIDADE),
	CONSTRAINT FK_CDD_ESD FOREIGN KEY (IDESTADO) REFERENCES TBESTADO(IDESTADO)
) ENGINE=INNODB DEFAULT CHARSET=UTF8;