CREATE TABLE TBENDERECO (
	IDENDERECO BIGINT NOT NULL AUTO_INCREMENT,
	TXLOGRADOURO VARCHAR(255) NOT NULL,
	TXNUMERO VARCHAR(255) NOT NULL,
	TXCOMPLEMENTO VARCHAR(255) NULL,
	TXBAIRRO VARCHAR(255) NOT NULL,
	NRCEP BIGINT NOT NULL,
	IDCIDADE BIGINT NOT NULL,
	CONSTRAINT PK_END PRIMARY KEY (IDENDERECO),
	CONSTRAINT FK_END_CDD FOREIGN KEY (IDCIDADE) REFERENCES TBCIDADE(IDCIDADE)
) ENGINE=INNODB DEFAULT CHARSET=UTF8;